### ISSUE TITLE
Make plugin available officially, at addons.mozilla.org

### ISSUE THREAD

**Issue by jf** [evacchi/firefox-custom-badge#2]
hi, first up, I love this plugin. It's the perfect complement to using multiple profiles! I dont have any complaints generally; but wish this plugin were available officially as mentioned. That way, users get ease of search, install, as well as added assurance. Is it possible to make the plugin available at addons.mozilla.org?

**Comment by Noitidart** [comment]
I hooked it up to use images and uploaded, check it out @jf and @evacchi  :)

https://addons.mozilla.org/en-US/firefox/addon/os-x-dock-icon-changer/
